### ISSUE TITLE
Problem accessing /. Reason:      Not Found

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1354]
Debian 10 Server. Upgraded to version 2.6 and enabled SSH plugin.

Reason for this was even increasing the client buffer of NGINX to an enormous limit did not help in adding an existing local repo to SCM-Manager. To be complete: _HTTP 413 CURL 22 error_ which is was trying to fix with _client_max_body_size_

Now when surfing to the homepage I get:
HTTP ERROR 404
Problem accessing /. Reason:

    Not Found
Powered by Jetty:// 9.4.15.v20190215

In logfile scm-manager.log I see some disturbing WARNings:

2020-09-28 17:28:17.726 [main] [          ] INFO  sonia.scm.lifecycle.classloading.ClassLoaderLifeCycle - create new simple ClassLoaderLifeCycle
2020-09-28 17:28:17.734 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextFilter - register for restart events
2020-09-28 17:28:17.741 [main] [          ] INFO  sonia.scm.event.LegmanScmEventBus - create new event bus ScmEventBus-1
2020-09-28 17:28:17.883 [main] [          ] INFO  sonia.scm.event.ScmEventBus - use sonia.scm.event.LegmanScmEventBus as event bus implementation
2020-09-28 17:28:18.003 [main] [          ] INFO  sonia.scm.lifecycle.BootstrapContextListener - start scm-manager initialization
2020-09-28 17:28:19.028 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - collect plugins
2020-09-28 17:28:19.144 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-review-plugin@2.3.0
+- scm-activity-plugin@2.0.0
+- scm-redmine-plugin@2.0.0
+- scm-git-plugin@2.6.0
+- scm-legacy-plugin@2.6.0
+- scm-hg-plugin@2.6.0
+- scm-readme-plugin@2.0.0
+- scm-ssh-plugin@2.1.0
+- scm-issuetracker-plugin@2.0.1
   +- scm-redmine-plugin@2.0.0
+- scm-landingpage-plugin@1.2.0
   +- scm-review-plugin@2.3.0
+- scm-pushlog-plugin@2.1.1
+- scm-mail-plugin@2.2.0
   +- scm-review-plugin@2.3.0
   +- scm-notify-plugin@2.0.1
+- scm-directfilelink-plugin@2.0.0
+- scm-svn-plugin@2.6.0
+- scm-statistic-plugin@2.0.0
+- scm-notify-plugin@2.0.1

2020-09-28 17:28:20.218 [main] [          ] INFO  sonia.scm.update.repository.XmlRepositoryV1UpdateStep - no v1 repositories database file found
2020-09-28 17:28:20.603 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.HgServletModule
2020-09-28 17:28:20.603 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.activity.ActivityModule
2020-09-28 17:28:20.603 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.SvnServletModule
2020-09-28 17:28:20.603 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class com.cloudogu.scm.ssh.auth.AuthModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.web.GitServletModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class com.cloudogu.scm.review.ModuleBinder
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.legacy.LegacyModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.mail.internal.MailModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.redmine.config.MapperModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.security.gpg.GPGModule
2020-09-28 17:28:20.604 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class com.cloudogu.scm.ssh.SshModule
2020-09-28 17:28:20.605 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.notify.NotifyModule
2020-09-28 17:28:20.606 [main] [          ] INFO  sonia.scm.lifecycle.modules.ApplicationModuleProvider - add module class sonia.scm.notify.NotifyConfigurationsModule
2020-09-28 17:28:20.635 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.filter.BaseUrlFilter to filter chain
2020-09-28 17:28:20.636 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.security.TokenExpiredFilter to filter chain
2020-09-28 17:28:20.636 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.security.ApiAuthenticationFilter to filter chain
2020-09-28 17:28:20.636 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.legacy.LegacyProtocolServletAuthenticationFilter to filter chain
2020-09-28 17:28:20.637 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.filter.DefaultHttpProtocolServletAuthenticationFilter to filter chain
2020-09-28 17:28:20.637 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.web.security.TokenRefreshFilter to filter chain
2020-09-28 17:28:20.637 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind filter class sonia.scm.filter.MDCFilter to filter chain
2020-09-28 17:28:20.638 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.lifecycle.RestartServlet to servlet chain
2020-09-28 17:28:20.638 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.web.protocol.HttpProtocolServlet to servlet chain
2020-09-28 17:28:20.638 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.web.i18n.I18nServlet to servlet chain
2020-09-28 17:28:20.640 [main] [          ] INFO  sonia.scm.filter.WebElementModule - bind servlet class sonia.scm.WebResourceServlet to servlet chain
2020-09-28 17:28:20.645 [main] [          ] INFO  sonia.scm.util.ScmConfigurationUtil - load ScmConfiguration from file /var/lib/scm/config/config.xml
2020-09-28 17:28:20.671 [main] [          ] INFO  sonia.scm.plugin.DefaultExtensionProcessor - start processing extensions
2020-09-28 17:28:20.672 [main] [          ] WARN  sonia.scm.plugin.ExtensionBinder - could not find extension for extension point interface sonia.scm.api.v2.resources.LogoutRedirection
2020-09-28 17:28:20.677 [main] [          ] WARN  sonia.scm.plugin.ExtensionBinder - could not find extension for extension point interface sonia.scm.io.FileSystem
2020-09-28 17:28:20.723 [main] [          ] INFO  sonia.scm.plugin.DefaultExtensionProcessor - bound extensions in 51.72 ms
2020-09-28 17:28:20.822 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.DefaultRealm
2020-09-28 17:28:20.823 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.legacy.LegacyRealm
2020-09-28 17:28:20.823 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.web.security.AdministrationContextRealm
2020-09-28 17:28:20.823 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class com.cloudogu.scm.ssh.auth.PublicKeyRealm
2020-09-28 17:28:20.824 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.BearerRealm
2020-09-28 17:28:20.824 [main] [          ] INFO  sonia.scm.lifecycle.modules.ScmSecurityModule - bind security realm class sonia.scm.security.AnonymousRealm
2020-09-28 17:28:22.403 [main] [          ] WARN  sonia.scm.cache.GuavaCacheConfigurationReader - could not find manual configuration at /var/lib/scm/ext/gcache.xml
2020-09-28 17:28:22.711 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.HgRepositoryHandler for type Type{name=hg, displayName=Mercurial}
2020-09-28 17:28:22.712 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.GitRepositoryHandler for type Type{name=git, displayName=Git}
2020-09-28 17:28:22.712 [main] [          ] INFO  sonia.scm.repository.DefaultRepositoryManager - added RepositoryHandler class sonia.scm.repository.SvnRepositoryHandler for type Type{name=svn, displayName=Subversion}
2020-09-28 17:28:23.188 [main] [          ] INFO  com.cloudogu.scm.ssh.ConfigurationApplier - setting ssh server port to 2223
2020-09-28 17:28:23.283 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.284 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.296 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.297 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.MyEventHandler
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.user.DefaultUserManager
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.PluginInstalledEventSubscriber
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.api.v2.resources.GitRepositoryConfigChangeClearRepositoryCacheListener
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.pullrequest.landingpage.PullRequestCreatedEventMapper
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.comment.service.CommentService
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.config.ScmConfigurationChangedListener
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.RepositoryPushEventSubscriber
2020-09-28 17:28:23.352 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.security.AuthorizationChangedEventProducer
2020-09-28 17:28:23.353 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.ProcessChangedFilesHook
2020-09-28 17:28:23.353 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.DefaultRepositoryRoleManager
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.user.AnonymousUserDeletionEventHandler
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.events.EventListener
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.pullrequest.service.RemoveReviewMarksOnChangedCommentsHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.issuetracker.internal.IssuePostReceiveRepositoryHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.GitRepositoryModifyListener
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.LastModifiedUpdateListener
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.pushlog.PushlogHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.RepositoryCreatedEventSubscriber
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.MergeObstacleCheckHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.emailnotification.EmailNotificationHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.activity.ActivityManager
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.PullRequestInformationHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.PluginCenterNotAvailableEventSubscriber
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.notify.NotifyRepositoryHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.BranchProtectionHook
2020-09-28 17:28:23.367 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.ssh.StartupContextListener
2020-09-28 17:28:23.368 [main] [          ] INFO  com.cloudogu.scm.ssh.ConfigurationApplier - setting ssh server port to 2223
2020-09-28 17:28:23.368 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.statistic.StatisticListener
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.repository.RemoveDeletedRepositoryRole
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.PluginInstallationFailedEventSubscriber
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.myevents.RepositoryRenamedEventSubscriber
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton sonia.scm.issuetracker.internal.IssueRepositoryListener
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.landingpage.favorite.RemoveDeletedRepositoryFavorites
2020-09-28 17:28:23.369 [main] [          ] INFO  sonia.scm.lifecycle.modules.EagerSingletonModule - initialize eager singleton com.cloudogu.scm.review.StatusCheckHook
2020-09-28 17:28:23.379 [main] [          ] INFO  sonia.scm.activity.CacheWarmUpListener - start cache warm up
2020-09-28 17:28:23.388 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.activity.CacheWarmUpListener$CacheWarmUpAction in administration context
2020-09-28 17:28:23.493 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.493 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
2020-09-28 17:28:23.490 [ActivityCacheWarmUp] [          ] INFO  sonia.scm.web.security.AdministrationContextRealm - assign admin permissions to admin context user scmsystem
2020-09-28 17:28:23.524 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.repository.HealthCheckContextListener$HealthCheckStartupAction in administration context

followed by a series of repository health checks. Bu then next followed by some warnings:

2020-09-28 17:28:23.639 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.statistic.StatisticBootstrapAction in administration context
2020-09-28 17:28:23.641 [main] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.lifecycle.SetupContextListener$SetupAction in administration context
2020-09-28 17:28:23.669 [main] [          ] INFO  com.cloudogu.scm.ssh.ScmSshServer - start ssh server

2020-09-28 17:28:24.239 [ActivityCacheWarmUp] [          ] WARN  sonia.scm.repository.GitUtil - could not find repository head in directory /var/lib/scm/repositories/git/bacula-tools/data
2020-09-28 17:28:24.242 [ActivityCacheWarmUp] [          ] WARN  org.eclipse.jgit.lib.Repository - close() called when useCnt is already zero for Repository[/var/lib/scm/repositories/git/bacula-tools/data]
2020-09-28 17:28:24.258 [ActivityCacheWarmUp] [          ] WARN  org.eclipse.jgit.lib.Repository - close() called when useCnt is already zero for Repository[/var/lib/scm/repositories/git/NagiosPlugin-validator/data]

Quite a series of my repos seem to have issues like this!

2020-09-28 17:28:30.483 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:29:00.482 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:29:30.482 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:30:00.482 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:30:30.482 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:31:00.482 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:31:30.483 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:32:00.482 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context
2020-09-28 17:32:30.483 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$323/0x0000000840602c40 in administration context

**Comment by pfeuffer** [comment]
We found a bug in 2.6.0 yesterday, which leeds to a "not found" when you have an empty mercurial repository and the readme plugin installed.

When you do have a mercurial repository, what you can do is this: delete the <scm-home>/plugins/scm-readme-plugin folder and restart the server. Does this help?

If you do not have an empty mercurial repository, can you give us more details about the error (there should be some body content, too).

We will release a bugfix release soon.

**Comment by eheimbuch** [comment]
Hey olaf7, 
we just released a bugfix release with version 2.6.1 which you can find here: https://www.scm-manager.org/download/2.6.1/

This should fix your problem.

**Comment by olaf7** [comment]
Great! Thank you. Looking forward for the **apt/.deb release**.
Regarding my repositories: I do have some Hg repos, but they are not empty. They were never used with SCM-Manager v2 but were with V1. Most of my repos are Git based. These gave errors as well.
I have my hopes for the 2.6.1 release as I wonder if removing the scm-readme-plugin directory will cut it as that would probably keep left over references in XML files?

**Comment by olaf7** [comment]
I manually installed 2.6.1 as the apt repo is broken at the moment.
Sad news: error remains

```
2020-09-30 13:56:46.483 [main] [          ] WARN  sonia.scm.template.ServletMustacheFactory - could not find resource sonia/scm/mail/layout_en.mustache
2020-09-30 13:56:46.483 [main] [          ] WARN  sonia.scm.template.MustacheTemplateEngine - could not find mustache template at /sonia/scm/mail/layout_en.mustache
```

followed by some repos being processed without errors and some with. Not sure, but I think they are not all Hg repos.

But also:
```
2020-09-30 13:56:47.005 [ActivityCacheWarmUp] [          ] WARN  sonia.scm.repository.GitUtil - could not find repository head in directory /var/lib/scm/repositories/git/bacula-tools/data

2020-09-30 13:56:47.116 [ActivityCacheWarmUp] [          ] WARN  sonia.scm.repository.HgHookManager - created url .... without request, in some cases this could cause problems

```

**Comment by sdorra** [comment]
Could you test accessing the scm-manager api directly (bypassing the nginx)? E.g.:

```
curl http://localhost:8080/scm/api/v2
```

Do you get a json output?

**Comment by olaf7** [comment]
```
# curl http://localhost:8080/scm/api/v2
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /scm/api/v2. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.15.v20190215</a><hr/>

</body>
</html>
```

**Comment by sdorra** [comment]
The running version is not a 2.6.0 nor 2.6.1. The Jetty Version should be 9.4.31.v20200723. Could you check if the process was restarted after the manual package installation? If not, please restart the process.

**Comment by olaf7** [comment]
```
root@f1:~# ps fax |grep jetty |grep scm
28952 ?        Ssl    0:40 /usr/bin/java -Djava.awt.headless=true -Dlogback.configurationFile=logging.xml -Djetty.host=0.0.0.0 -Djetty.port=8080 -classpath :/opt/scm-server/conf:/opt/scm-server/lib/* -Dapp.name=scm-server -Dapp.pid=28952 -Dapp.repo=/opt/scm-server/lib -Dbasedir=/opt/scm-server sonia.scm.server.ScmServerDaemon
root@f1:~# service scm-server stop
root@f1:~# ps fax |grep jetty |grep scm
root@f1:~# service scm-server start
root@f1:~# service scm-server status
● scm-server.service - SCM-Manager Server
   Loaded: loaded (/etc/systemd/system/scm-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-09-30 16:36:02 CEST; 3s ago
 Main PID: 29429 (java)
    Tasks: 26 (limit: 65000)
   Memory: 156.7M
   CGroup: /system.slice/scm-server.service
           └─29429 /usr/bin/java -Djava.awt.headless=true -Dlogback.configurationFile=logging.xml -Djetty.host=0.0.0.0 -Djetty.port=8080 -classpath :/opt/scm-server/

Sep 30 16:36:02 f1 systemd[1]: Started SCM-Manager Server.
Sep 30 16:36:02 f1 scm-server[29429]: 2020-09-30 16:36:02.860:INFO::main: Logging initialized @546ms to org.eclipse.jetty.util.log.StdErrLog
Sep 30 16:36:03 f1 scm-server[29429]: 2020-09-30 16:36:03.685:INFO:oejs.Server:main: jetty-9.4.31.v20200723; built: 2020-07-23T17:57:36.812Z; git: 450ba27947e13e66ba
root@f1:~# curl http://localhost:8080/scm/api/v2
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /scm/api/v2. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.15.v20190215</a><hr/>

</body>
</html>

root@f1:~# dpkg -l |grep scm
ii  scm-server                            2.6.1                                all          The easiest way to share and manage your Git, Mercurial and Subversion repositories

```

**Comment by sdorra** [comment]
This is super weird, the jetty prints the right version in the log but the website shows the wrong one?

Are you sure there is only one SCM-Manager instance running? No docker container (`docker ps`)? No other java process (`ps -ef | grep java`, please check all java processes jetty is not always in the command args)? No jsvc processes from old installations (`ps -ef | grep jsvc`)?

How did you do the manual installation?

**Comment by olaf7** [comment]
I double checked both. Yes, Java processes are running, but none related to scm-manager. Next I rebooted the server. No change. Error persists.

**Comment by sdorra** [comment]
Could you double check that the jetty, which is running on port 8080, is the scm-manager process?

```bash
lsof -i :8080
systemctl status scm-server
```

Please compare the "PID" from the lsof output with the "Main PID" from the systemctl output.

**Comment by olaf7** [comment]
```
root@f1:~# ps -ef | grep jsvc
root      1412  1108  0 11:20 pts/0    00:00:00 grep jsvc
root@f1:~# systemctl status scm-server
● scm-server.service - SCM-Manager Server
   Loaded: loaded (/etc/systemd/system/scm-server.service; enabled; vendor preset: enabled
   Active: active (running) since Wed 2020-09-30 18:08:53 CEST; 17h ago
 Main PID: 660 (java)
    Tasks: 34 (limit: 65000)
   Memory: 436.1M
   CGroup: /system.slice/scm-server.service
           └─660 /usr/bin/java -Djava.awt.headless=true -Dlogback.configurationFile=loggin

Warning: Journal has been rotated since unit was started. Log output is incomplete or unav
root@f1:~# ps faux | grep scm
scm        660  0.2  3.6 4650708 294396 ?      Ssl  Sep30   2:24 /usr/bin/java -Djava.awt.headless=true -Dlogback.configurationFile=logging.xml -Djetty.host=0.0.0.0 -Djetty.port=8080 -classpath :/opt/scm-server/conf:/opt/scm-server/lib/* -Dapp.name=scm-server -Dapp.pid=660 -Dapp.repo=/opt/scm-server/lib -Dbasedir=/opt/scm-server sonia.scm.server.ScmServerDaemon
root      1587  0.0  0.0   6144   888 pts/0    S+   11:21   0:00                      \_ grep scm

```

**Comment by sdorra** [comment]
Please post the output of the **lsof** command `lsof -i :8080`, we must be sure that the process running on port 8080 is the same which is started by systemd.

**Comment by olaf7** [comment]
After much digging I indeed found an interfering process. Weird that I did not find it earlier. Also quite strange that during an upgrade port config has changed without me being aware of it. Nasty. Thanks for the support and sorry for not spotting it earlier.
