### ISSUE TITLE
LDAP Plugin is Spamming scm-manager.log

### ISSUE THREAD

**Issue by StenaviN** [scm-manager/scm-manager#1529]
## Issue description

LDAP plugin endlessly spams log every few milliseconds:
```
2021-02-08 13:04:08.178 [qtp36333492-214078] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user tc-merc-interop-svc executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.178 [qtp36333492-214078] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.193 [qtp36333492-219994] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user tc-merc-interop-svc executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.193 [qtp36333492-219994] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.256 [qtp36333492-221122] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user _anonymous executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.256 [qtp36333492-221122] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.287 [qtp36333492-207529] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user _anonymous executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.287 [qtp36333492-207529] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.287 [qtp36333492-221122] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user tc-merc-interop-svc executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.287 [qtp36333492-221122] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.350 [qtp36333492-207529] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user tc-merc-interop-svc executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.350 [qtp36333492-207529] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
2021-02-08 13:04:08.365 [qtp36333492-217092] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - user _anonymous executes sonia.scm.security.SyncingRealmHelper$$Lambda$423/0x000000080076ac40 as admin
2021-02-08 13:04:08.365 [qtp36333492-217092] [          ] INFO  sonia.scm.user.DefaultUserManager - modify user tc-merc-interop-svc of type ldap
```

Also, LDAP users go back and force to Internal and External even I turn on "Enabled User Converter" option.

#### Describe your SCM-Manager setup

SCM-Manager 2.13.0

**Comment by pfeuffer** [comment]
Thanks for this report. I'll take a look at this right now.

**Comment by pfeuffer** [comment]
Am I right that this happens whenever you use SVN? We have an open pull request for the LDAP plugin that should fix this (scm-manager/scm-ldap-plugin#15). This should be released soon, but we need to have another core release for this fix first.

**Comment by StenaviN** [comment]
No, we use Mercurial.

--
  Mykola Ivanets

вт, 16 лют. 2021, 10:56 користувач René Pfeuffer <notifications@github.com>
пише:

**Comment by pfeuffer** [comment]
Ok, checked this. The fix mentioned above works for Mercurial, too.

**Comment by pfeuffer** [comment]
This should be fixed now with the new version of the LDAP plugin (v2.2.0). This requires an update of SCM-Manager to v2.14.0, too. Can you please check, whether this solves your issue, @StenaviN ? Thank you!

**Comment by StenaviN** [comment]
@pfeuffer Sure, I'll update SCM-Manager and come back.

**Comment by StenaviN** [comment]
@pfeuffer 2.14.1 - still the same endless messages in the log

**Comment by pfeuffer** [comment]
This is weird, @StenaviN . Have you updated the LDAP Plugin to version 2.2.0, too?

**Comment by StenaviN** [comment]
Oh, my bad. I only update SCM Manager. Will update plugins in non-operational time and come back with response.

**Comment by StenaviN** [comment]
I still get the same behavior. Should I restart SCM Manager after updating plugins via UI?

**Comment by pfeuffer** [comment]
Yes, you have to restart at least once, either by clicking "Execute Updates" or restarting manually.

**Comment by helmut72** [comment]
I have the same messages in the log file, every 30 seconds:

```
2021-05-14 22:01:30.679 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
2021-05-14 22:01:30.943 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
2021-05-14 22:02:00.680 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
2021-05-14 22:02:00.943 [CronScheduler-1-1] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
2021-05-14 22:02:30.679 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
2021-05-14 22:02:30.942 [CronScheduler-1-2] [          ] INFO  sonia.scm.web.security.DefaultAdministrationContext - execute action sonia.scm.schedule.PrivilegedRunnableFactory$$Lambda$589/0x00000001008e0840 in administration context
```

Only using Git.
